spring:
  application:
    name: appoint
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/scloud?serverTimezone=GMT%2B8
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

girl:
  age: 23

