
    
spring:
 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
